name: RegionCheck
main: me.chris.RegionCheck.RegionCheckMain
version: 1.0
description: A plugin.
depend: [Vault]
commands:
    regioncheck:
        description: This command is the base command for the entire plugin.
        usage: /<command>
    rgc:
        description: This is the same thing as using pt, except longer... So pretty useless.
        usage: /<command>